# Ansible managed: /ansible/roles/postgresql/templates/database.yml.j2 modified on 2015-10-12 17:29:44 by vagrant on localhost

default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: councils

  username: vagrant
  password: None

test:
  <<: *default
  database: councils_test
